In [1]:
import pandas as pd
import numpy as np
from Utilities import Model_evaluation

In [2]:
df = pd.read_csv('./Data/analysis_data.csv',encoding='utf-16')
df_duration = pd.read_csv('./Data/duration_survey_df.csv',encoding='utf-16')

In [3]:
final_df = pd.read_csv('./Data/Final_video.csv',encoding='utf-16')
final_list = final_df['Project_Id'].tolist()

In [4]:
video_df = df_duration[['Project_Id','duration']]
video_df = video_df.rename(columns = {'duration':'video_duration'})

In [5]:
final_df = pd.merge(df,video_df,how='left')

In [6]:
# 최종 1002개 비디오만 추출
final_video_df = pd.read_csv('./Data/Final_video.csv',encoding='utf-16')
final_list = final_video_df['Project_Id'].tolist()
final_df = final_df[final_df.Project_Id.isin(final_list)]

In [7]:
final_df.shape

(1002, 36)

In [8]:
final_df.columns.tolist()

['Project_Id',
 'Project_launched_at',
 'Project_deadline',
 'Project_goal',
 'Project_category',
 'Date',
 'Days_to_go',
 'Pledged',
 'Options_number',
 'Title_count',
 'Blurb_count',
 'Content_text_length',
 'Content_img_count',
 'Faq_count',
 'Update_count',
 'Comment_count',
 'Backers',
 'Video_name',
 'Cancel_check',
 'Project_title',
 'Project_blurb',
 'Backed_count',
 'Created_count',
 'num_crawl',
 'duration',
 'diff',
 'Success',
 'backer1',
 'backer2',
 'backer3',
 'ratio1',
 'ratio2',
 'ratio3',
 'Top_category',
 'super_category',
 'video_duration']

In [9]:
Analysis_df = final_df[['duration','Project_goal','video_duration','Update_count','Project_blurb','Faq_count',\
    'Created_count','Backed_count','ratio1','ratio2','ratio3','backer1','backer2','backer3','Success']]

In [10]:
# Project_blurb
Analysis_df['Project_blurb'] = Analysis_df['Project_blurb'].apply(lambda x : len(x))
# Backed_count
Analysis_df['Backed_count'] = Analysis_df['Backed_count'].apply(lambda x : 0 if x =='None' else x)
Analysis_df['Backed_count'] = Analysis_df['Backed_count'].apply(lambda x : float(x))

/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

Se

## Model evaluation

In [11]:
model = Model_evaluation.Model_evaluation(Analysis_df,'Success',scaler='std')

### Random forest

In [12]:
model.random_forest()

RF : 0.8308157099697885
             precision    recall  f1-score   support

          0       0.85      0.79      0.82       162
          1       0.81      0.87      0.84       169

avg / total       0.83      0.83      0.83       331

[0.8358209  0.82587065 0.79104478 0.86       0.84422111]


/Users/yonggeol/workspace/Kickstarter/Utilities/Model_evaluation.py:39: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  clf.fit(self.x_train, self.y_train)
/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConv

### SVM

In [13]:
model.svm()

/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVM : 0.7643504531722054
             precision    recall  f1-score   support

          0       0.77      0.75      0.76       162
          1       0.76      0.78      0.77       169

avg / total       0.76      0.76      0.76       331



/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[0.60199005 0.80099502 0.80597015 0.785      0.77386935]


### Logistic regression

In [14]:
model.logistic_regression()

/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/sklearn/linear_model/sag.py:326: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


logistic_regression
LR : 0.7583081570996979
             precision    recall  f1-score   support

          0       0.76      0.74      0.75       162
          1       0.76      0.78      0.77       169

avg / total       0.76      0.76      0.76       331



/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/sklearn/linear_model/sag.py:326: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/sklearn/linear_model/sag.py:326: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

[0.51741294 0.46268657 0.46268657 0.465      0.46733668]


/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/sklearn/linear_model/sag.py:326: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/sklearn/linear_model/sag.py:326: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

### MLP

In [15]:
model.mlp()

/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:912: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Iteration 1, loss = 0.67869098
Iteration 2, loss = 0.61091536
Iteration 3, loss = 0.57727876
Iteration 4, loss = 0.56354450
Iteration 5, loss = 0.55171476
Iteration 6, loss = 0.54162361
Iteration 7, loss = 0.52970147
Iteration 8, loss = 0.51945154
Iteration 9, loss = 0.51519552
Iteration 10, loss = 0.50731106
Iteration 11, loss = 0.50005855
Iteration 12, loss = 0.49323682
Iteration 13, loss = 0.48965063
Iteration 14, loss = 0.48287943
Iteration 15, loss = 0.47716594
Iteration 16, loss = 0.47561643
Iteration 17, loss = 0.46801110
Iteration 18, loss = 0.46780938
Iteration 19, loss = 0.46368552
Iteration 20, loss = 0.45895796
Iteration 21, loss = 0.45647612
Iteration 22, loss = 0.45468534
Iteration 23, loss = 0.45373089
Iteration 24, loss = 0.45000930
Iteration 25, loss = 0.44779092
Iteration 26, loss = 0.44540300
Iteration 27, loss = 0.44455523
Iteration 28, loss = 0.44244179
Iteration 29, loss = 0.43966923
Iteration 30, loss = 0.44034766
Iteration 31, loss = 0.43655376
Iteration 32, los

/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (35) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
