In [1]:
import pandas as pd
import numpy as np
import Model_evaluation

In [2]:
df = pd.read_csv('analysis_data.csv',encoding='utf-16')
df_duration = pd.read_csv('duration_survey_df.csv',encoding='utf-16')

In [3]:
video_df = df_duration[['Project_Id','duration']]
video_df = video_df.rename(columns = {'duration':'video_duration'})

In [4]:
final_df = pd.merge(df,video_df,how='left')

In [5]:
final_df.shape

(1315, 36)

In [14]:
final_df.columns.tolist()

['Project_Id',
 'Project_launched_at',
 'Project_deadline',
 'Project_goal',
 'Project_category',
 'Date',
 'Days_to_go',
 'Pledged',
 'Options_number',
 'Title_count',
 'Blurb_count',
 'Content_text_length',
 'Content_img_count',
 'Faq_count',
 'Update_count',
 'Comment_count',
 'Backers',
 'Video_name',
 'Cancel_check',
 'Project_title',
 'Project_blurb',
 'Backed_count',
 'Created_count',
 'num_crawl',
 'duration',
 'diff',
 'Success',
 'backer1',
 'backer2',
 'backer3',
 'ratio1',
 'ratio2',
 'ratio3',
 'Top_category',
 'super_category',
 'video_duration']

In [7]:
Analysis_df = final_df[['duration','Project_goal','video_duration','Update_count','Project_blurb','Faq_count',\
    'Created_count','Backed_count','ratio1','ratio2','ratio3','backer1','backer2','backer3','Success']]

In [8]:
# Project_blurb
Analysis_df['Project_blurb'] = Analysis_df['Project_blurb'].apply(lambda x : len(x))
# Backed_count
Analysis_df['Backed_count'] = Analysis_df['Backed_count'].apply(lambda x : 0 if x =='None' else x)
Analysis_df['Backed_count'] = Analysis_df['Backed_count'].apply(lambda x : float(x))

/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

Se

## Model evaluation

In [9]:
model = Model_evaluation.Model_evaluation(Analysis_df,'Success',scaler='std')

### Random forest

In [10]:
model.random_forest()

RF : 0.8502304147465438
             precision    recall  f1-score   support

          0       0.88      0.80      0.84       210
          1       0.83      0.89      0.86       224

avg / total       0.85      0.85      0.85       434

[0.84848485 0.84030418 0.85931559 0.80988593 0.84351145]


/Users/yonggeol/workspace/Research/[2019]Kickstarter_Crwodsourcing/Kickstarter/Data explore/Model_evaluation.py:39: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  clf.fit(self.x_train, self.y_train)
/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:458: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/sklearn/

### SVM

In [11]:
model.svm()

/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was pass

SVM : 0.7119815668202765
             precision    recall  f1-score   support

          0       0.66      0.85      0.74       210
          1       0.80      0.58      0.68       224

avg / total       0.73      0.71      0.71       434

[0.73863636 0.84030418 0.82509506 0.7338403  0.55725191]


/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


### Logistic regression

In [12]:
model.logistic_regression()

logistic_regression
LR : 0.695852534562212
             precision    recall  f1-score   support

          0       0.64      0.84      0.73       210
          1       0.79      0.56      0.65       224

avg / total       0.72      0.70      0.69       434



/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/sklearn/linear_model/sag.py:326: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/sklearn/linear_model/sag.py:326: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did n

[0.48863636 0.49809886 0.48288973 0.4904943  0.48473282]


/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/sklearn/linear_model/sag.py:326: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


### MLP

In [13]:
model.mlp()

Iteration 1, loss = 0.68934652
Iteration 2, loss = 0.61295851
Iteration 3, loss = 0.58956972
Iteration 4, loss = 0.58243894
Iteration 5, loss = 0.57384495
Iteration 6, loss = 0.56377280
Iteration 7, loss = 0.55639344
Iteration 8, loss = 0.54938822
Iteration 9, loss = 0.54462142
Iteration 10, loss = 0.53894662
Iteration 11, loss = 0.53612746
Iteration 12, loss = 0.53254718
Iteration 13, loss = 0.52830048
Iteration 14, loss = 0.52666460
Iteration 15, loss = 0.52314804
Iteration 16, loss = 0.52006322
Iteration 17, loss = 0.51762528
Iteration 18, loss = 0.51640406
Iteration 19, loss = 0.51356079
Iteration 20, loss = 0.51111760
Iteration 21, loss = 0.51061333
Iteration 22, loss = 0.50773615
Iteration 23, loss = 0.50751820
Iteration 24, loss = 0.50405023
Iteration 25, loss = 0.50299440
Iteration 26, loss = 0.50125412
Iteration 27, loss = 0.50014685
Iteration 28, loss = 0.49975432
Iteration 29, loss = 0.49820799
Iteration 30, loss = 0.49604506
Iteration 31, loss = 0.49458736
Iteration 32, los

/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:912: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/yonggeol/miniconda3/envs/py/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (35) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
